#!/usr/bin/env bash
# Configure the gateway VM:
#   - static IP on the LAN segment interface
#   - IPv4 forwarding
#   - nftables: forward ONLY sandbox-lan -> VPN tunnel (kill-switch), masquerade on tunnel
#   - pin the gateway's own DNS on the WAN connection
#
# Run as root inside the gateway VM:  su -  &&  bash scripts/gateway/setup-gateway.sh
set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run as root: su -"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../config.env
source "${SCRIPT_DIR}/../config.env"

echo "==> Installing packages"
apt-get update -qq
apt-get install -y nftables

echo "==> LAN interface ${LAN_IFACE} -> ${GATEWAY_IP}/${PREFIX} (no default route, IPv6 off)"
if nmcli -t -f NAME connection show | grep -qx "lan"; then
    nmcli connection modify lan \
        connection.interface-name "${LAN_IFACE}" \
        ipv4.method manual ipv4.addresses "${GATEWAY_IP}/${PREFIX}" \
        ipv4.never-default yes ipv6.method disabled
else
    nmcli connection add type ethernet ifname "${LAN_IFACE}" con-name lan \
        ipv4.method manual ipv4.addresses "${GATEWAY_IP}/${PREFIX}" \
        ipv4.never-default yes ipv6.method disabled
fi
nmcli connection up lan

echo "==> Enabling IPv4 forwarding"
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-forward.conf
sysctl --system >/dev/null

echo "==> Writing /etc/nftables.conf (forward only ${LAN_IFACE} -> ${VPN_IFACE})"
cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# Generated by setup-gateway.sh
# Kill-switch: forwarded traffic may leave ONLY through the VPN tunnel.
flush ruleset

table inet filter {
    chain forward {
        type filter hook forward priority 0; policy drop;
        iifname "${LAN_IFACE}" oifname "${VPN_IFACE}" accept
        iifname "${VPN_IFACE}" oifname "${LAN_IFACE}" ct state established,related accept
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oifname "${VPN_IFACE}" masquerade
    }
}
EOF
nft -c -f /etc/nftables.conf
systemctl enable nftables
systemctl restart nftables

echo "==> Pinning gateway DNS to ${DNS} on '${WAN_CON}'"
if nmcli -t -f NAME connection show | grep -qxF "${WAN_CON}"; then
    nmcli connection modify "${WAN_CON}" ipv4.dns "${DNS}" ipv4.ignore-auto-dns yes
    nmcli connection up "${WAN_CON}"
else
    echo "    WARNING: connection '${WAN_CON}' not found - set WAN_CON in config.env and re-run, or fix DNS manually."
fi

echo
echo "==> Done. With the VPN connected, verify the sandbox path goes into the tunnel:"
echo "    ip r get 1.1.1.1 from ${CLIENT_IP} iif ${LAN_IFACE}      # expect: dev ${VPN_IFACE}"
echo "    nft list ruleset"
